export default {
  type: 'object',
  properties: {
    nombre: { type: 'string' },
    altura: { type: 'string' },
    peso: { type: 'string' },
    color_cabello: { type: 'string' },
    color_piel: { type: 'string' },
    color_ojos: { type: 'string' },
    ano_nacimiento: { type: 'string' },
    sexo: { type: 'string' },
    tierra_natal: { type: 'string' },
    peliculas: { type: 'array', items: { type: 'string' } },
    especies: { type: 'array', items: { type: 'string' } },
    vehiculos: { type: 'array', items: { type: 'string' } },
    naves: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'nombre',
    'altura',
    'peso',
    'color_cabello',
    'color_piel',
    'color_ojos',
    'ano_nacimiento',
    'sexo',
    'tierra_natal',
    'peliculas',
    'especies',
    'vehiculos',
    'naves',
  ],
} as const;
